# Generated by Django 2.2.8 on 2020-03-24 19:26

from django.db import migrations
import express_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('express_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', express_auth.models.UserManager()),
            ],
        ),
    ]
