# Generated by Django 2.2.8 on 2020-03-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express_auth', '0002_auto_20200325_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='offer_confirmed',
            new_name='verified',
        ),
    ]
